# Final project checkpoint 2

###### Michelle Schlacks


###### IS 445

### WRITE UP

###### - One paragraph explaining how to use the dashboard you created, to help someone who is not an expert understand your dataset.
    - The dashboard I created is two plots. The first is a scatter plot which will help you look at the number of fatal shootings based on age. Each of the little plusses represents the amount of fatalities that have happened at the age that is on the y axis. Then the second plot is a plot that will show you the total victims based on location. The interactive aspect I have added is that you can choose how you want to view the plots. 
###### - A list of 1 or more contextual datasets you have identified, links to where they reside, and a sentence about why they might be useful in telling the final story.
    - The dataset I am using can be found on data.world, I went through about 5 datasets trying to get them to work following the assignment 6 type of dashboard. But as you can see I was not able to complete that. So, I settled on doing some basic plots with this dataset. Here is the link: https://data.world/nick612hayden/shootingsintheusa/workspace/file?filename=shootings.csv
    - I think this will be useful, because I think it will be quite interesting to look at the different states and realize where the most shootings happen etc.

### CODE

In [2]:
import pandas as pd
import matplotlib 
import matplotlib.pyplot as plt

import numpy as np
%matplotlib inline
import ipywidgets
from ipywidgets import interactive
from datetime import datetime
import bqplot

In [3]:
df = pd.read_csv('/Users/michelleschlacks/Desktop/shootings.csv', encoding = "unicode_escape")

In [4]:
#df = df.fillna()
df

,Case,Location,Date,Year,Summary,Fatalities,Injured,Total victims,Venue,Prior signs of mental health issues,...,Mental Health Sources,latitude,longitude,Type,City,State,Murderers,Age,Add'l notes on Total Victims,Location_Standardized
0,Stoneman Douglas High School shooting,"Parkland, Florida",2018-02-14,2018,"Nikolas J. Cruz, 19, heavily armed with an AR-...",17,14,31,School,Yes,...,https://www.nytimes.com/2018/02/15/us/nikolas-...,NaN,NaN,Mass,Parkland,FL,Nikolas J. Cruz,19,31+,"Parkland, FL"
1,Pennsylvania carwash shooting,"Melcroft, PA",2018-01-28,2018,"Timothy O'Brien Smith, 28, wearing body armor ...",4,1,5,Other,TBD,...,NaN,NaN,NaN,Mass,Melcroft,PA,Timothy O'Brien Smith,28,NaN,"Melcroft, PA"
2,Rancho Tehama shooting spree,"Rancho Tehama, CA",2017-11-14,2017,"Kevin Janson Neal, 44, went on an approximatel...",5,10,15,Other,TBD,...,NaN,NaN,NaN,Spree,Rancho Tehama,CA,Kevin Janson Neal,44,NaN,"Rancho Tehama, CA"
3,Texas First Baptist Church massacre,"Sutherland Springs, TX",2017-11-05,2017,"Devin Patrick Kelley, a 26-year-old ex-US Air ...",26,20,46,Religious,Yes,...,http://www.expressnews.com/news/local/article/...,32.780105,-96.800008,Mass,Sutherland Springs,TX,Devin Patrick Kelley,26,46+,"Sutherland Springs, TX"
4,Walmart shooting in suburban Denver,"Thornton, CO",2017-11-01,2017,"Scott Allen Ostrem, 47, walked into a Walmart ...",3,0,3,Other,Unclear,...,NaN,43.060567,-88.106479,Mass,Thornton,CO,Scott Allen Ostrem,47,NaN,"Thornton, CO"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Shopping centers spree killings,"Palm Bay, Florida",1987-04-23,1987,"Retired librarian William Cruse, 59, was paran...",6,14,20,Other,Yes,...,(Supreme Court of Florida Document) http://www...,33.749099,-84.390185,Spree,Palm Bay,FL,Retired librarian William Cruse,59,NaN,"Palm Bay, FL"
93,United States Postal Service shooting,"Edmond, Oklahoma",1986-08-20,1986,"Postal worker Patrick Sherrill, 44, opened fir...",15,6,21,Workplace,Unclear,...,http://newsok.com/sherrill-feared-mental-illne...,42.098687,-75.917974,Mass,Edmond,OK,Postal worker Patrick Sherrill,44,NaN,"Edmond, OK"
94,San Ysidro McDonald's massacre,"San Ysidro, California",1984-07-18,1984,"James Oliver Huberty, 41, opened fire in a McD...",22,19,41,Other,Yes,...,http://www.nctimes.com/news/local/article_2ba4...,41.685632,-72.729838,Mass,San Ysidro,CA,James Oliver Huberty,41,NaN,"San Ysidro, CA"
95,Dallas nightclub shooting,"Dallas, Texas",1984-06-29,1984,"Abdelkrim Belachheb, 39, opened fire at an ups...",6,1,7,Other,Yes,...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,33.787794,-117.853112,Mass,Dallas,TX,Abdelkrim Belachheb,39,NaN,"Dallas, TX"
96,Welding shop shooting,"Miami, Florida",1982-08-20,1982,"Junior high school teacher Carl Robert Brown, ...",8,3,11,Other,Yes,...,http://news.google.com/newspapers?id=uuYLAAAAI...,33.559859,-81.721952,Mass,Miami,FL,Junior high school teacher Carl Robert Brown,51,NaN,"Miami, FL"

In [5]:
@ipywidgets.interact(style=plt.style.available)
def make_plot(style):
    with plt.style.context(style): # this style is applied ONLY to this plot and not following
        fig, ax = plt.subplots(1,1,figsize=(6,3))
        ax.scatter(df["Age"], df["Fatalities"], marker= '+')
        ax.set_xlabel("Age")
        ax.set_ylabel("Fatalities")
        ax.set_yscale('linear')
        ax.set_xscale('linear')



    plt.show()
    
    
#interactive_plot = interactive(make_plot)
#output = interactive_plot.children[-1]
#output.layout.height = '350px'
#interactive_plot

interactive(children=(Dropdown(description='style', options=('Solarize_Light2', '_classic_test_patch', 'bmh', …

In [6]:
df["Location"]
#df["Total victims"]

0          Parkland, Florida
1               Melcroft, PA
2          Rancho Tehama, CA
3     Sutherland Springs, TX
4               Thornton, CO
               ...
92         Palm Bay, Florida
93          Edmond, Oklahoma
94    San Ysidro, California
95             Dallas, Texas
96            Miami, Florida
Name: Location, Length: 97, dtype: object

In [7]:
@ipywidgets.interact(style=plt.style.available)
def make_plot(style):
    with plt.style.context(style):
        fig, ax = plt.subplots(1,1,figsize=(6,3))
        ax.bar(df["Location_Standardized"], df["Total victims"])
        ax.set_xlabel("Location_Standardized")
        ax.set_ylabel("Total victims")
        ax.set_yscale('linear')        
    plt.show()

interactive(children=(Dropdown(description='style', options=('Solarize_Light2', '_classic_test_patch', 'bmh', …

In [8]:
#df['Year'] = pd.to_datetime(df['Year'], format='%Y')

In [8]:
#Y = list(df["Year"])
#X = list(df["APPEARANCES"].unique())
#print(X)
#print(Y)

#plt.bar(X, Y)
#plt.show()
#X = df["APPEAR"].values
#Y = df["Year"].values

#print(X)
#print(Y)

#print(len(X))
#print(len(Y))

#plt.bar(X,Y)
#plt.show()

In [9]:
#X = df["CountyTotalVotes"].values
#Y = df["PrecintsReporting"].values

#plt.scatter(X, Y)

In [10]:
#type(df["CountyTotalVotes"].values.astype(int))
#type(df["CountyTotalVotes"].values.tolist())

In [11]:
#col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
#x_sc = bqplot.LinearScale() # ordered, categorical data, because our bins are more like categorical bins
#y_sc = bqplot.LinearScale()

# 3. Marks
#barplot = bqplot.Bars(x=df["CountyTotalVotes"].values.tolist(), y= df["PrecintsReporting"].values.tolist(), scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                           #interactions={'click':'select'},
                           #anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
#c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
#x_ax = bqplot.Axis(scale=x_sc)
#y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

In [12]:
#def on_selected(change): # take a look at what changes when I select a new bin
    #print(change['owner'].selected)
#bar_plot.observe(on_selected,'selected')

In [13]:
#df['Year'] = pd.to_datetime(df['Year'], format='%Y')
#dfheatmap = pd.pivot_table(df,  index=["STATE AGENCY"],
 #                               values=["SQUARE FEET"],
  #                              columns=["COUNTY"],
   #                             aggfunc=np.mean)

In [14]:
#type(df["arrest_type_description"].values)

In [15]:
#col_sc = bqplot.ColorScale(scheme='inferno')
#x_sc = bqplot.OrdinalScale() 
#y_sc = bqplot.OrdinalScale()

In [16]:
#col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
#x_ax = bqplot.Axis(scale=x_sc, label='ID', label_offset='100px',tick_rotate=60,tick_style={'font-size':'7px'})
#y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='name', tick_style={'font-size':'5px'})

In [17]:
#anames = dfheatmap.columns.levels[1].to_list() 
#print((dfheatmap.values))
#df["SQUARE FEET"]

In [18]:
#
#data = np.random.randn(10, 10)


#heat_map = bqplot.GridHeatMap(color = np.log10(dfheatmap.values),
 #                             row = dfheatmap.index, 
  #                            column = anames,
   #                           scales = {'color': col_sc,
    #                                    'row': y_sc,
     #                                   'column': x_sc},
      #                        interactions = {'click': 'select'},
       #                       anchor_style = {'fill':'blue'}, 
      #                        selected_style = {'opacity': 1.0},
       #                       unselected_style = {'opacity': 1.0})'''

In [19]:
#fig.layout.min_width='500px'
#figures = ipywidgets.HBox([fig])
#fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
#myDashboard = ipywidgets.VBox([fig])
#myDashboard'''

In [20]:

#
#x_scl = bqplot.DateScale()
#y_scl = bqplot.LinearScale()

#ax_xcl = bqplot.Axis(label='County Name', scale=x_scl)
#ax_ycl = bqplot.Axis(label='Square footage in year acquired', scale=y_scl, 
#                   orientation='vertical', side='left')

In [21]:
#'''i,j = 0,0
#mask = (df['CountyName'] == dfheatmap.index[i]) & \
#       (df['PrecintsReporting'] == dfheatmap.columns.levels[1][j])
#subset = df[mask]'''

In [22]:
#'''group = subset.groupby("CountyTotalVotes")["PrecintsReporting"].sum()
#years = group.index
#sqft = group.values'''